version: "3.3"

services:
  my_library:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - "/postgres_data:/var/lib/postgresql/data"
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@mail.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - 5000:80